### ISSUE TITLE
Mise à jour de nos références

### ISSUE THREAD

**Issue by JulienParis** [multi-coop/multi-site-contents#100]
⚠️ Issue à splitter en autant d'issues que de références à rajouter.

### Problème :

La page de notre site listant nos références n'est pas à jour. 

Plusieurs projets - que nous avons terminé ou actuellement en cours - sont absents. 

Je peux en oublier ou me tromper, mais voici une première liste de références absentes tirée de notre [CRM](https://gitlab.com/multi-coop/crm/-/boards/3908374).

- [ ] [[DGAL/Scopyleft] - ma-cantine](https://gitlab.com/multi-coop/crm/-/issues/85)
- [ ] [[ADEME/MALT] Transition écologique des entreprises (TEE)](https://gitlab.com/multi-coop/crm/-/issues/82)
- [ ] [[CGDD] ecologie.data.gouv.fr](https://gitlab.com/multi-coop/crm/-/issues/103)
- [ ] [[NGI SEARCH 4] Datami v2](https://gitlab.com/multi-coop/crm/-/issues/111)
- [ ] [[ANSM / Atol CD] GDR Santé (phase 2](https://gitlab.com/multi-coop/crm/-/issues/85) (cf aussi [phase 1](https://gitlab.com/multi-coop/crm/-/issues/97))
- [ ] [[DGITM / Fairness] - DiaLog](https://gitlab.com/multi-coop/crm/-/issues/80)
- [ ] [Plateforme des talents - La Zone](https://plateformedestalents.la.zone/) (g rien trouvé dans le CRM?)
- [ ] [[Grist Labs] Partenariat Suite numérique](https://gitlab.com/multi-coop/crm/-/issues/110)
- [ ] [[Hub Francil'in] Développement d'une plateforme de supervision pour le dispositif "Numérique pour tous"](https://gitlab.com/multi-coop/crm/-/issues/105)
- [ ] [[CGDD / Datactivist] Catalogage GD4H](https://gitlab.com/multi-coop/crm/-/issues/108)

### Ma proposition :

Les personnes volontaires et/ou impliquées sur les projets peuvent : 

- Se signaler sur cette issue pour indiquer quelle(s) référence(s) ils ou elles souhaitent ajouter à nos références
  - Si une référence n'a pas vocation à être publiée sur notre site, merci de préciser en commentaire
- Créer une nouvelle issue dédiée sur ce repo et mettre à jour le listing dans la description de cette issue
  - Voir § suivant pour la marche à suivre en pratique
- Faire une branche et une PR dédiée, référence par référence si nécessaire, et maj cette issue. 

En ce qui me concerne je me propose pour faire le suivi de cette issue, et si personne ne se porte volontaire de faire la fiche TEE.

### Guide pratique pour ajouter une référence :

- 1 - Créer une branche pour la/les références, avec un nom du genre `update-references-<CODE_PROJET>`

- 2 - Créer un nouveau fichier `<CODE_PROJET>.md` dans le sous-répertoire [`./texts/references/projects`](https://github.com/multi-coop/multi-site-contents/tree/main/texts/references/projects) 
  - Ce fichier est à écrire sous la même forme que les autres, c'est-à-dire que l'essentiel est écrit dans le block `yaml` du fichier markdown (voir [exemple](https://raw.githubusercontent.com/multi-coop/multi-site-contents/refs/heads/main/texts/references/projects/africartes.md)) 
  - Penser à ajouter la/les illustration(s) dans le dossier [`./images/references`](https://github.com/multi-coop/multi-site-contents/tree/main/images/references) dans un sous-dossier au nom du projet : `/images/references/<CODE_PROJET>/<CODE_PROJET>-001.png/jpg`

- 3 - Ajouter le lien vers la référence dans le fichier [`./texts/references/references-data.md`](https://raw.githubusercontent.com/multi-coop/multi-site-contents/refs/heads/main/texts/references/references-data.md)

- 4 - PR + merge + c'est tout, ça apparaîtra dans le site automatiquement une fois mergé
  - Exemple du projet [Validata dans nos références](https://www.multi.coop/references?locale=fr&item=.%2Ftexts%2Freferences%2Fprojects%2Fvalidata.md)
